server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
        prefix-enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USER:-eureka}:${EUREKA_PASSWORD:-password123}@${EUREKA_HOST:discovery-server}:8763/eureka/}

jwt:
  secret: ${JWT_SECRET:my-very-long-and-secure-jwt-secret-key-that-is-at-least-512-bits-long-so-it-works-with-shopease-microservices}

management:
  endpoints:
    web:
      exposure:
        include: health,gateway
  endpoint:
    health:
      show-details: always

resilience4j:
  timelimiter:
    instances:
      orderServiceCB:
        timeoutDuration: 10s
      inventoryServiceCB:
        timeoutDuration: 10s
  circuitbreaker:
    instances:
      orderServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 60
        slowCallDurationThreshold: 8s
        slowCallRateThreshold: 80
