server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
              - "https://shop.praveen-challa.tech"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      default-filters:
        - name: PreserveHostHeader
      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
        prefix-enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/products(?<segment>.*), /api/v1/products${segment}
        - id: category-service
          uri: lb://product-service
          predicates:
            - Path=/api/categories/**
          filters:
            - RewritePath=/api/categories(?<segment>.*), /api/v1/categories${segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: oauth2-auth
          uri: lb://user-service
          predicates:
            - Path=/oauth2/**
        - id: oauth2-login
          uri: lb://user-service
          predicates:
            - Path=/login/oauth2/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USER:-eureka}:${EUREKA_PASSWORD:-password123}@${EUREKA_HOST:discovery-server}:8763/eureka/}

jwt:
  secret: ${JWT_SECRET:my-very-long-and-secure-jwt-secret-key-that-is-at-least-512-bits-long-so-it-works-with-shopease-microservices}

management:
  endpoints:
    web:
      exposure:
        include: health,gateway
  endpoint:
    health:
      show-details: always

resilience4j:
  timelimiter:
    instances:
      orderServiceCB:
        timeoutDuration: 10s
      inventoryServiceCB:
        timeoutDuration: 10s
  circuitbreaker:
    instances:
      orderServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 60
        slowCallDurationThreshold: 8s
        slowCallRateThreshold: 80
